spring:
  application:
    name: Journal App
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: journaldb
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379

weather:
  api:
    key: ${WEATHER_API_KEY}

server:
  port: 8080
  servlet:
    context-path: /journal